### PR TITLE
Release 3.7.0

### PR DESCRIPTION
**Pull request by jesconstantine**
# Mayflower Release Notes

### SUMMARY
We've updated the topic page!

If you'd like to read about this changes in JIRA:

* [DP-2117](https://jira.state.ma.us/browse/DP-2117) - [pattern lab] Topic Page Updates

### Improvements
* We've updated the Topic page! (Pages > Topic State Parks and Recreation) - and we're talking more than just a new name (no more L1's here!):
   * The new header layout includes a a spot for a description and a nifty new image size.
    * We've introduced some new variations to the card component (Molecules > Section Links) on the Topic Page:
        * You can now choose between regular links (by default) or callout links (Molecules > Section Links Callout Links).  This will help to call out How-To's and tasks associated with a service on a given topic page.
        * For those times when we don't want to fill the card up with too many links but we want people to know there are more goodies, we've add an optional more link to the bottom of the card. 

Note: This PR contains the commits from release 3.6.0 (#382) because I squashed and merged that release, losing the commit history.

### CODE REVIEW

**Comment by jesconstantine** [comment]
To Test 3.7.0:

1. browse to staging (http://stage-mayflower.digital.mass.gov/) 
2. verify that the topic page (click the Pages nav item) has been renamed to: Topic State Parks and Recreation (vs L1 State Parks and Recreation)
3. verify that the topic page has a new banner layout with an 820 x 460 image (vs the standard 1600 by 400)
4. verify that the card (pattern is Molecules > section links) group shown has the following options displayed: 
- links in both text (decorative link) and button (callout link) format
- a more link at the bottom

To test for 3.6.0 regression:

1. verify that there is only 1 guide page (Pages > Movng to MA) and 1 guide example section page (Pages > Guide Section Example)
2. verify that on that guide page (Pages > Movng to MA) you see a horizontal section "Moving with Pets" that has no right side bar content
3. verify that the government organization schema meta pattern exists (Meta > Schema > Government Organization) then click the cog in the top right corner to "Show Pattern Info" to see the markup of this non-visual / semantic pattern.  You should also be able to see this pattern implemented in the Org Landing Page (Pages > Org Landing Page), "Show Pattern Info", click the "HTML" tab and scroll down to just before the `</main>` tag, above the `<footer>`

Thanks again @plusjeff

**Comment by jeffmaher** [comment]
@jesconstantine : Yikes! Sorry I'm so slow on this. We're trying to deploy Mass.gov Drupal stuff today, so I likely won't get to this today. If this is a problem, feel free to assign a different reviewer. Otherwise, I'm happy to review on Wednesday.

**Comment by jesconstantine** [comment]
No worries and thanks @plusjeff !  I just tapped @isaacchansky on the shoulder and he was able to go through for us.  Thanks to you both again!

**Review by isaacchansky — APPROVED** [review]
Running through the tests, everything looks good. 

Org page docs are  🔥

**Pull request merged**
