### PR TITLE
DP-1995 - Add nl2br filter to contact us address to allow new line instead of <br>

### PR DESCRIPTION
**Pull request by gleroux02**
Ticket: https://jira.state.ma.us/browse/DP-1995

Uses http://twig.sensiolabs.org/doc/2.x/filters/nl2br.html on the address in the contact group to allow the use of /n for a line break.

To test:
* Confirm that an address that is supposed to have a multi line break uses \n instead and that it renders properly.

### CODE REVIEW

**Review by gender404 — CHANGES_REQUESTED** [review]
You either missed a file or you accidentally changed an address that should have kept the ```<br />```.

The google-map.twig file has an address that is displayed in the map's Info Window.  I'm not sure if the address for Info Window should keep the ```<br />``` or be replaced with "\n" instead.

**Review by gender404 — APPROVED** [review]
I uploaded changes for the google map to match the same format

**Comment by gleroux02** [comment]
@legostud This leaves a <br> displaying in the pop up. Is google just looking to make it one line? If that is the case why don't we replace "/n" with just a space?
image

**Comment by gender404** [comment]
Your screen shot looks out of date.  Are you using the updated handlebar template?

image

**Pull request merged**
