### PR TITLE
DP-8602: Remove unused slick plugin

### PR DESCRIPTION
**Pull request by rbayliss**
Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/dev/docs/change-log-instructions.md)

## Description

Removes Slick Sllideshow javascript library, which wasn't being used.  

## Related Issue / Ticket

- [JIRA issue](https://jira.state.ma.us/browse/DP-8602)

## Steps to Test

1. Load the Mayflower start page and ensure that no errors are thrown in the javascript console.

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

### CODE REVIEW

**Review by mrossi113 — APPROVED** [review]
👍 LGTM!

**Comment by mrossi113** [comment]
FYI... I'm seeing a retired Google Map API version on Mayflower `Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version` which can be seen on the live website as well: https://www.mass.gov/visit-massachusetts-state-parks/locations. @rbayliss should I make a ticket?

**Comment by rbayliss** [comment]
@mrossi113 - Good call. I kind of forgot about that one.  Just created a followup: https://jira.state.ma.us/browse/DP-8804

**Review by ygannett — APPROVED** [review]
LGTM.  Nothing returns with 'slick-carousel' with grep.
Ready to merge.

**Pull request merged**
