### PR TITLE
DP-3225 Aria role for Wait Time

### PR DESCRIPTION
**Pull request by mrossi113**
To update the "Wait Time" with the aria role `role="status" aria-live=“polite”` to let the screen reader know when a change to the wait time has occurred. 

JIRA ticket https://jira.state.ma.us/browse/DP-3225

Testing:
This can't be tested in Mayflower for we don't have wait time being updated.

I used the live site RMV page `https://pilot.mass.gov/locations/natick-rmv-service-center` and added the `role="status" aria-live="polite"` into the inspector tool to test. I used Chrome and VoiceOver

Below are the screenshots:
 screen shot 2017-07-13 at 3 22 48 pm

screen shot 2017-07-13 at 3 23 12 pm

### CODE REVIEW

**Comment by jesconstantine** [comment]
@mrossi113 thanks for this update!  We could update the actual wait time app so the component is more accessible for anyone who implements it - what do you think?  Your could PR would be opened on that repo: https://github.com/massgov/rmvwaittime

**Comment by mrossi113** [comment]
@jesconstantine that sounds good! I will work on this today.

**Comment by mrossi113** [comment]
Leaving this open until we have figure out if the `rmvwaittime` repo will work with these changes in Drupal instance.

**Comment by mrossi113** [comment]
Closing this PR for not needed anymore. This work was done in the https://github.com/massgov/rmvwaittime/pull/5

**Pull request closed without merging**
