### PR TITLE
DP-3094 Service Detail

### PR DESCRIPTION
**Pull request by gender404**
Converted General Page to Service Detail page.
https://jira.state.ma.us/browse/DP-3094

1. Add more about section to the top of the page
2. Added a subtitle to the page header
3. Added Form Downloads and Key Action components to the page.
4. Removed sidebar promo
5. Added related links to right rail

### CODE REVIEW

**Comment by gender404** [comment]
@labbydev - please remember to "Squash and Merge" this PR when you feel it is complete.

**Comment by labbydev** [comment]
@legostud  this is also missing breadcrumbs

**Comment by gender404** [comment]
@labbydev  - Breadcrumbs aren't usually used with the more about tags (bubbles).

**Comment by labbydev** [comment]
ok

**Pull request merged**
