### PR TITLE
Dp 5914 service card spacing

### PR DESCRIPTION
**Pull request by clairesunstudio**
## Description
On all breakpoints:
Decrease the bottom margin on .ma_section-links_title to .5em from 1em
The callout links are getting extra padding applied to them (40px on desktop and 20px on tablet and mobile). This should be removed.
Example: https://www.mass.gov/topics/seniors
Mayflower matches the example and also has the extra padding: http://mayflower.digital.mass.gov/?p=pages-topic
servicecards

## Related Issue / Ticket

- [JIRA issue](https://jira.state.ma.us/browse/DP-5914)
- Github issue: n/a

## Steps to Test
- Before: [Mayflower Topic Page](http://mayflower.digital.mass.gov/?p=pages-topic)
- After: [UAT Topic Page](http://clairesun.com/mayflower/?p=pages-topic)
- [ ] Decrease the bottom margin on .ma_section-links_title
- [ ] Remove extra padding on callout links

## Screenshots
- Before
mayflower_topic_page

- After
mayflower_topic_page_new

### CODE REVIEW

**Review by mariohernandez — APPROVED** [review]
Looks good.  Should the margin value have a leading zero since is less than 1? (i.e. `margin-bottom: 0.5em;`).
Not sure if that's a practice on this project.

**Comment by mariohernandez** [comment]
It looks like conflicts need to be cleared.

**Comment by clairesunstudio** [comment]
@mariohernandez, looks like leading zeros are omitted in other places (there are other cases in this file). let me know if it's supposed to be added.

**Comment by clairesunstudio** [comment]
I think the conflicts are because of DP-5915 getting merged. I will rebase.

**Pull request closed without merging**
