### PR TITLE
DP-8203 Mayflower display issues

### PR DESCRIPTION
**Pull request by ygannett**
Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/dev/docs/change-log-instructions.md)

## Description

Header alert content was not displayed in the full space of its given width (See the before screenshot below) in Firefox.  It was displayed fine in webkit browsers.  Some CSS had been removed to prevent this issue.  The missing CSS has been added as a fix.

"+" button for the contact accordion for the main column was shown in the side column contact (See the before screenshot below).  The button markup was not in the condition to render in the main column only.  The markup for the button has been moved under the condition to be rendered only in the main column.

## Related Issue / Ticket

- [DP-8203 Mayflower display issues](https://jira.state.ma.us/browse/DP-8203)

### Header Alert
1. Go to the Location Park Content page (/?p=pages-location-park-content).

2. Find the sample header alerts are displayed in one line each as shown in the after screenshot below.

### Contact in Side column
1. Go to the Board Decision page (/?p=pages-board-decision) in Firefox.

2. No "+" is shown on the right side in the browser.

3. Check the source for the side column contact.

4. Find no `span.ma__contact-us--accordion__status` after `h3.ma__column-heading` as shown in the after screenshot below. 

#### Before
header-alert_before
#### After
header-alert_after

#### Before
decision_before
#### After
decision_after

## Additional Notes:
It would be helpful if external reviewer test in multiple browsers for any Mayflower changes.

#### Impacted Areas in Application

* 

#### @TODO

*

### CODE REVIEW

**Comment by rbayliss** [comment]
Both of these changes make sense to me and fix the issue locally, although it looks like we've got a conflict here.  @ygannett, could you update this PR when you get a chance?

**Comment by rbayliss** [comment]
@ygannett - It looks like the accordion trigger is back after resolving the merge conflict: 

screen shot 2018-03-16 at 12 22 02 pm

**Comment by ygannett** [comment]
@rbayliss The fix has been applied.  I'm sorry that I should have checked it when I worked on the merge conflicts.  Would you take a look again?

**Comment by rbayliss** [comment]
Much better. Looks good to me.  Thanks @ygannett!

**Review by rbayliss — APPROVED** [review]

**Review by yriahi — APPROVED** [review]
This looks good to me. Thanks @ygannett

**Pull request merged**
