### PR TITLE
Add current mass.gov logo in header to mayflower assets

### PR DESCRIPTION
**Pull request by avrilpearl**
Adds the current mass.gov site logo for the header of the website to mayflower's image assets.
- add current logo into image assets
- change Atoms/Media/Site Logo to the current logo
- add option to hide back to button in header conditionally
- hide back to button on homepage

### CODE REVIEW

**Review by clairesunstudio — APPROVED** [review]
I think we can just switch the pilot logo to this current logo

**Comment by clairesunstudio** [comment]
@isaacchansky do you know how mass.gov is hiding the back-to-classic button in the header? we just added a conditional rendering for that button, and I am curious if there're any changes need to be made in the mass repo

**Comment by isaacchansky** [comment]
I believe mass.gov doesn't use the templates for that page level stuff, it's recreated and omits that markup: https://github.com/massgov/mass/blob/develop/docroot/themes/custom/mass_theme/templates/layout/page.html.twig

**Comment by clairesunstudio** [comment]
@isaacchansky interesting, why is the override necessary? Doesn't seem like this pr is changing anything on the Mass.gov side of things. Are you okay if I merge this in?

**Comment by isaacchansky** [comment]
I'm not sure why it's necessary, but yeah I don't believe this affects the drupal stuff - it's cool with me!

**Pull request merged**
