### PR TITLE
DP-3911 - Form page

### PR DESCRIPTION
**Pull request by gender404**
# Create Form Page:
https://jira.state.ma.us/browse/DP-3911

## Goals:
1. Create form input styling needed for Mass.gov's form stack.
2. Generate a basic form page layout in Pattern as an example of the inputs and messaging
3. Added basic error handling

### New Patterns:
1. Helper Text - atom - text below an input describing what to enter
2. Input Group - atom - stacked or inline group of radio buttons or checkboxes
3. Textarea - atom - was input-textarea, but renamed and enhanced to include max-length functionality
4. SVG icons - bg-checklist.svg, svg-cash.svg, svg-check.svg, svg-credit.svg, svg-input-error.svg, svg-question-mark.svg
5. Error List - molecule - list of labels associated to inputs with errors
6. Divided Inputs - molecule - and inline group of inputs separated by a custom divider
7. Tooltip - molecule - text below an input that opens a small modal describing what to enter in more detail
8. Form Requirements - organism - list of required items for a form along with payment type.
9. Basic Form - template
10. Basic Form Example - page

### Modified Patterns:
1. Input Checkbox - atom - converted the `checked` variable from type string to type boolean
2. Input Radio - atom - converted the `checked` variable from type string to type boolean
3. Input Text - atom - 
    - new fields:
        * hiddenLabel - boolean - toggles the visibility on the inputs label
        * type - string - populates the inputs type attribute (text, email, number, file, ...)
        * width - number - populates an inline width style
        * errorMsg - string - used for an inline error message located above the input
    - Added modifier classes to the label to show the `(optional)` text for optional inputs
    - New styling for type number and type file
    - New JS functionality for type number to increment value and restrict it to number values.
4. Input-textarea - atom - renamed to textarea
5. Select-box - atom - added `required` boolean value to toggle `(optional)` message on the label
6. Location Icons - molecule - updated the title to use a `title` variable and made it optional
7. Feedback Form - organism - updated to use input text for email and new textarea fields

### Updated inputText Data for type="text" (backward compatible since inputs are type text by default)
1. Event Filters - molecule
2. Field Submit - molecule
3. Location Filters - molecule
4. Banner Form - organism
5. Location Listing - organism
6. Search Banner - organism
7. Event Listing - page
8. Location Listing - page

### Deleted Patterns:
1. input Email - atom - removed in favor of input-text with type="email"

### Fixes:
1. Added popupOffsets.js to helpers (not part of bundle) for future work on the tooltip

### CODE REVIEW

**Comment by labbydev** [comment]
@legostud reviewing the Error List Molecule returns a blank WSOD page. I am seeing the following error in console:
````
:3000/patterns/02-molecules/index.html?1498597093598:227 Uncaught TypeError: Cannot read property 'patternType' of undefined
````

**Review by labbydev — APPROVED** [review]

**Comment by isaacchansky** [comment]
The tooltip component isn't accessible via a screen reader - see attached gif (of voiceover trying to get to it to read it). happy to chat if gif doesn't make sense. 
cvv-tooltip-accessibility

Invalid stuff looks awesome, but also some accessibility issues there - the summary and list of errors is read out which is great, though you can't seen to navigate back to read it again if you missed it, and the 'links'(labels) within that summary section are not accessible to a screen reader.

**Comment by gender404** [comment]
@isaacchansky - I debated making the error list 'links' instead of 'labels'.  The label approach accomplished the desired scroll and focus without needing JavaScript.  Also from what I found on the below site, "These fields listed can be links to the field in error but are not required to be links because the fields in error are already identified. Providing links can assist users in quickly jumping to the field in error.", it didn't seem to be an issue for accessibility which didn't require them to be links.

From the gif it appears that the screen reader can't read the content of the tool tip.  Is that the issue you are seeing?

**Comment by isaacchansky** [comment]
@legostud the field explanation makes sense, thanks for clarifying. Yeah the tooltip next isn't able to be read via a screenreader as far as I can tell.

**Pull request merged**
