### PR TITLE
Refs MGRP-252, Updates the contact group.

### PR DESCRIPTION
**Pull request by lukewertz**
This adds handling for links, fax numbers, and removed the link-based default treatment for data. Also removes the colons from the labels.

### CODE REVIEW

**Comment by gender404** [comment]
I feel this there where I need to explain the complexity of changing JSON data.  By removing the colon here and making it content, we now need to update every other JSON file that includes a Contact Group label to make sure all of the items in Pattern Lab still show a colon.

Mainly coming from the Contact Us and the Header Contact organisms.

ContactUs:
C:\sandboxes\mayflower\styleguide\source\_patterns\02-molecules\contact-us.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\02-molecules\contact-us~linked-title.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\03-organisms\by-author\multi-row-section.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\03-organisms\by-author\sidebar-contact.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\ACTION-get-a-state-park-pass.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\GUIDE-movng-to-ma-part1.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\GUIDE-movng-to-ma-part2.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\GUIDE-movng-to-ma-part3.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\LOC-Mt-Greylock-State-Park.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\LOC-Southbridge-RMV.json:

headerContact:
C:\sandboxes\mayflower\styleguide\source\_patterns\02-molecules\header-contact.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\02-molecules\header-contact.twig:
C:\sandboxes\mayflower\styleguide\source\_patterns\03-organisms\by-template\action-header.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\03-organisms\by-template\action-header.twig:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\LOC-Mt-Greylock-State-Park.json:
C:\sandboxes\mayflower\styleguide\source\_patterns\05-pages\LOC-Southbridge-RMV.json:

**Comment by lukewertz** [comment]
@jasonstanbery Should that be done as part of this PR or a followup?

**Comment by lukewertz** [comment]
Also: This really seems like something that should be refactored and simplified. This level of complexity for something like contact information indicates a very brittle system that doesn't have a lot of internal cohesion.

I'd recommend we make a followup PR that accomplishes the big goal here which should be to simplify this complexity.

Lastly, if the colon is content, then it doesn't *need* to be in the example data. If you'd like it to be, or by convention it should, then yes--you'll need to update other json files that render using this Twig template; but making that a hard dependency of this PR seems to be counter to the spirit of the request.

**Comment by jasonstanbery** [comment]
@lukewertz What _exact_ scenario are we trying to fix here?

> There are some of the label fields in the contact area that automatically have colons and others do not. This has to be really awkward for editors :-)

Are we trying to make a more generic field to reuse instead of having multiple fields that each have a separate twig template on the drupal implementation side? I feel like we're widening the guardrails to make implementation easier and increasing the opportunity for inconsistency in the contact group.

From our perspective, we really want the colons there in that component. And if they're moving to the content, I'd really like to see it updated everywhere because other agencies are currently using the patterns, and we want the colons there.

**Comment by lukewertz** [comment]
@jasonstanbery I didn't know other agencies were using these patterns yet. Which ones? I'd love to learn about how they're approaching some things.

That said: it sounds like your push back should be directed to the content team. The request to have these removed originated there; the content team put colons in all their labels manually because they wanted to control when the colons were appear.

If you have concerns about the workload, I'm sure that Christine Flynn would be happy to negotiate that conversation with you and the editorial team.

My expectation is, that in order to close launch-blocking bug tickets, one of two things will either happen:
1) I will get specific implementation feedback on how to get this PR to a point where you can merge it quickly
2) You will merge this PR

Please let me know what the outcome of any conversation you have with Christine or the editorial team is. Thanks.

**Comment by jasonstanbery** [comment]
@lukewertz @legostud - just trying to figure out where the confusion lies for the content team. As a user, if I'm presented a label field & value field my instinct wouldn't tell me I needed to add a separator, but that might be what they're used to.

To the real issue, to get it through we just need to update all the static content. Whether it's in this PR or one shortly after I don't care.

**Comment by lukewertz** [comment]
For the sake of getting this ready for release tomorrow, I'm override this in the Mass.gov theme. You can see what I've done here: https://github.com/massgov/mass/blob/fe11f2df2cc68ef0576ea0eb546e6e8d3f9576aa/web/themes/custom/mass_theme/templates/includes/molecule-contact-group.html.twig

When/If this is merged, I'll be able to revert back to using the Pattern Lab-provided twig file.

Thanks for your input on this!

**Comment by gender404** [comment]
I will state my disapproval with this that I have sent up the chain, but I also doubt that communication will change the outcome of this PR, being that the content team, lacking proper direction, incorrectly entered the ":" and now the dev team has to fix that mistake.

It also feels that Luke is not going to spend the time required to make sure that the prototypes in Pattern Lab continue to match the designs that were approved by making sure the colon is still shown.

**Pull request merged**
